# Generated by Django 3.0.4 on 2020-05-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200505_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='mood',
            field=models.CharField(choices=[('A', 'angry'), ('B', 'melancholy'), ('cheerful', 'cheerful'), ('D', 'calm'), ('E', 'romantic'), ('F', 'mysterious')], default='A', max_length=20),
        ),
    ]
