# Generated by Django 3.0.4 on 2020-05-05 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200505_0122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='posted_by',
            new_name='posted_by_id',
        ),
    ]
