# Generated by Django 3.0.6 on 2020-05-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200507_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='mood',
            field=models.CharField(choices=[('angry', 'Angry'), ('melancholy', 'Melancholy'), ('cheerful', 'Cheerful'), ('calm', 'Calm'), ('romantic', 'Romantic'), ('mysterious', 'Mysterious')], default='angry', max_length=20),
        ),
    ]
