# Generated by Django 3.0.6 on 2020-05-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200507_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='mood',
            field=models.CharField(choices=[('Angry', 'Angry'), ('Melancholy', 'Melancholy'), ('Cheerful', 'Cheerful'), ('Calm', 'Calm'), ('Romantic', 'Romantic'), ('Mysterious', 'Mysterious')], default='Angry', max_length=20),
        ),
    ]
