# Generated by Django 3.0.6 on 2020-05-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20200507_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='mood',
            field=models.CharField(choices=[('angry', 'angry'), ('melancholy', 'melancholy'), ('cheerful', 'cheerful'), ('calm', 'calm'), ('romantic', 'romantic'), ('mysterious', 'mysterious')], default='angry', max_length=20),
        ),
    ]
